//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_v1_4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MusicTypes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MusicTypes()
        {
            this.UserMusicTypes = new HashSet<UserMusicTypes>();
        }
    
        public int MusicTypeId { get; set; }
        public string MusicTypeName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserMusicTypes> UserMusicTypes { get; set; }
    }
}
