//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_v1_4.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FindMyPartyEntities : DbContext
    {
        public FindMyPartyEntities()
            : base("name=FindMyPartyEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Countries> Countries { get; set; }
        public virtual DbSet<Currency> Currency { get; set; }
        public virtual DbSet<Drink> Drink { get; set; }
        public virtual DbSet<Food> Food { get; set; }
        public virtual DbSet<MusicTypes> MusicTypes { get; set; }
        public virtual DbSet<PrivateParty> PrivateParty { get; set; }
        public virtual DbSet<PrivatePartyDrink> PrivatePartyDrink { get; set; }
        public virtual DbSet<ToBring> ToBring { get; set; }
        public virtual DbSet<UserMusicTypes> UserMusicTypes { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
