//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_v1_4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PrivateParty
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PrivateParty()
        {
            this.PrivatePartyDrink = new HashSet<PrivatePartyDrink>();
            this.PrivatePartyDrink1 = new HashSet<PrivatePartyDrink>();
            this.PrivatePartyDrink2 = new HashSet<PrivatePartyDrink>();
            this.Food = new HashSet<Food>();
        }
    
        public int PrivatePartyId { get; set; }
        public string HostUserId { get; set; }
        public System.DateTime StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string DescriptionName { get; set; }
        public string LineAdress { get; set; }
        public string PostCode { get; set; }
        public string City { get; set; }
        public string CountryId { get; set; }
        public string DressCode { get; set; }
        public Nullable<decimal> ParticipationFee { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PrivatePartyDrink> PrivatePartyDrink { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PrivatePartyDrink> PrivatePartyDrink1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PrivatePartyDrink> PrivatePartyDrink2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Food> Food { get; set; }
    }
}
