//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_v1_4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PrivatePartyDrink
    {
        public int PrivatePartyId { get; set; }
        public int DrinkItemId { get; set; }
    
        public virtual Drink Drink { get; set; }
        public virtual Drink Drink1 { get; set; }
        public virtual PrivateParty PrivateParty { get; set; }
        public virtual PrivateParty PrivateParty1 { get; set; }
        public virtual PrivateParty PrivateParty2 { get; set; }
    }
}
